language: php

dist: trusty

addons:
  apt:
    packages:
      # Needed for `xmllint`.
      - libxml2-utils

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm/.cache

branches:
  only:
    - master

install:
  - composer install
  - if [[ $WP_TRAVISCI == *"test"* ]]; then composer global require phpunit/phpunit "^$PHPUNIT_VERSION"; fi
  - nvm install --lts && nvm use --lts
  - npm install
  - npm run build && rm -r build

script:
  - if [[ $WP_TRAVISCI == *"lint"* ]]; then npm run lint; fi
  - if [[ $WP_TRAVISCI == *"test"* ]]; then npm run test; fi

jobs:
  include:
    - stage: test
      php: "7.3"
      env: WP_VERSION=trunk  PHPUNIT_VERSION=7 WP_TRAVISCI=lint,phpunit
    - php: "7.2"
      env: WP_VERSION=latest PHPUNIT_VERSION=7 WP_TRAVISCI=phpunit
    - php: "7.1"
      env: WP_VERSION=latest PHPUNIT_VERSION=7 WP_TRAVISCI=phpunit
    - php: "7.0"
      env: WP_VERSION=latest PHPUNIT_VERSION=6 WP_TRAVISCI=phpunit
    - php: "5.6"
      env: WP_VERSION=latest PHPUNIT_VERSION=5 WP_TRAVISCI=phpunit
    - php: "5.6"
      env: WP_VERSION=latest PHPUNIT_VERSION=5 WP_TRAVISCI=phpunit
